//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadTex.Models
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FollowUp
    {
        [Key]
        public int Id { get; set; }
        public string Topic { get; set; }
        public string ResultDesc { get; set; }
        [ForeignKey("User_Id")]
        public virtual ExtendedUser User { get; set; }
        [ForeignKey("Customer_Id")]
        public virtual Customer Customer { get; set; }
        public string User_Id { get; set; }
        public int Customer_Id { get; set; }
    }
}
