//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadTex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FutureAppointment
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> AppointmentWith { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
