//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadTex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> ReminderTime { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public Nullable<int> ReminderOffset { get; set; }
        public Nullable<int> IsRepeat { get; set; }
        public Nullable<int> RepeatInterval { get; set; }
        public Nullable<int> NoOfTimeRepeat { get; set; }
    }
}
